# Use a imagem base do Python
FROM python:3.8

# Copie o script Python para o diretório de trabalho no container
COPY mascarar_dados.py /app/mascarar_dados.py

# Defina o diretório de trabalho como /app
WORKDIR /app

# Execute o script Python quando o container for iniciado
CMD ["python", "mascarar_dados.py"]
